- name: oc_delete_svc
  hosts: all
  tasks:
  environment:
    KUBECONFIG: "/home/adminlocal/kubeconfig-orin"
  tasks:
  - name: Delete svc
    shell: oc delete -f svc.yaml --insecure-skip-tls-verify=true
    register: command_output
    args:
      chdir: /home/adminlocal/orin

  - debug:
      msg: "{{ command_output }}"