apiVersion: v1
kind: Service
metadata:
  name: nut-detection-service
spec:
  selector:
    app: nut-detection
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30000   # Specify the desired NodePort value here
  type: NodePort       # Use NodePort type for the service
