---
- name: Deploy to MicroShift 
  hosts: all
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Create a namespace
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: "{{namespace }}"

    - name: Apply Service Account 
      kubernetes.core.k8s:
        state: present
        template:
          - path: 'service-account.yaml.j2'

    - name: Create Security Context Constraint
      kubernetes.core.k8s:
        state: present
        template:
          - path: 'security-context-constraints.yaml.j2'

    - name: Apply Role Binding
      kubernetes.core.k8s:
        state: present
        template:
          - path: 'rb-template.yaml.j2'
    # Create a deployment config file then attempt to validate it to test it 
    - name: Create Deployment Config File
      template:
        src: dc-template.yaml.j2
        dest: /tmp/dc-template.yaml
      register: dc_file

    - name: fail on validation errors
      kubernetes.core.k8s:
        state: present
        definition: "{{ lookup('template', '/tmp/dc-template.yaml') | from_yaml }}"
        validate:
          fail_on_error: yes

    #- name: Apply MicroShift Deployment
    #  k8s:
    #    state: present
    #    template:
    #      - path: 'dc-template.yaml.j2'
    #  when: dc_validate.valid

    - name: Apply MicroShift Service
      k8s:
        state: present
        template:
          - path: 'svc-template.yaml.j2'