---
- name: Deploy to MicroShift 
  hosts: all
  gather_facts: no
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  tasks:
    - name: Create a namespace
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: "{{namespace }}"

   - name: Genereate Service Account file
      template:
        src: service-account.yaml.j2
        dest: "{{ output_path }}/service-account.yaml"  

    - name: Apply Service Account 
      kubernetes.core.k8s:
        state: present
        definition: "{{ output_path }}/service-account.yaml"

    - name: Generaete Role Binding
      template:
        src: rb-template.yaml.j2
        dest: "{{ output_path }}/rb-template.yaml.j2"  

    - name: Apply Role Binding
      kubernetes.core.k8s:
        state: present
        definition: "{{ output_path }}/rb-template.yaml"  

    - name: Render MicroShift Deployment
      template:
        src: dc-template.yaml.j2
        dest: "{{ output_path }}/deployment.yaml"  
      

    - name: Apply MicroShift Deployment
      k8s:
        state: present
        definition: "{{ output_path }}/deployment.yaml"  

    - name: Render MicroShift Service
      template:
        src: svc-template.yaml.j2 
        dest: "{{ output_path  }}/svc.yaml"

    - name: Apply MicroShift Service
      k8s:
        state: present
        definition: "{{ output_path  }}/svc.yaml"