---
- name: Deploy to OpenShift 
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create a namespace
      k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: rh1-pins-demo
    